version: '3.8'
services:
  dev:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: bughive
    networks:
      - freecodecamp
  test:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: bughive
    networks:
      - freecodecamp
networks:
  freecodecamp: